### ISSUE TITLE
Latest update (1.4.12) broke gdal/fiona

### ISSUE THREAD

**Issue by jorisvandenbossche** [AnacondaRecipes/kealib-feedstock#1]
The latest update of two days ago breaks creating a fresh environment from the default channel for the geo stack (using geopandas here, but is installs fiona, gdal, etc):

```
$ conda config --set restore_free_channel false
$ conda config --set channel_priority strict
$ conda create -n geo_test geopandas -c defaults
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/joris/miniconda3/envs/geo_test

  added / updated specs:
    - geopandas

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  attrs              pkgs/main/noarch::attrs-19.3.0-py_0
  blas               pkgs/main/linux-64::blas-1.0-mkl
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0
  ca-certificates    pkgs/main/linux-64::ca-certificates-2020.1.1-0
  cairo              pkgs/main/linux-64::cairo-1.14.12-h8948797_3
  certifi            pkgs/main/linux-64::certifi-2019.11.28-py38_0
  click              pkgs/main/noarch::click-7.0-py_0
  click-plugins      pkgs/main/noarch::click-plugins-1.1.1-py_0
  cligj              pkgs/main/linux-64::cligj-0.5.0-py38_0
  curl               pkgs/main/linux-64::curl-7.67.0-hbc83047_0
  expat              pkgs/main/linux-64::expat-2.2.6-he6710b0_0
  fiona              pkgs/main/linux-64::fiona-1.8.4-py38hc38cc03_0
  fontconfig         pkgs/main/linux-64::fontconfig-2.13.0-h9420a91_0
  freetype           pkgs/main/linux-64::freetype-2.9.1-h8a8886c_1
  freexl             pkgs/main/linux-64::freexl-1.0.5-h14c3975_0
  gdal               pkgs/main/linux-64::gdal-2.3.3-py38hbb2a789_0
  geopandas          pkgs/main/noarch::geopandas-0.6.1-py_0
  geos               pkgs/main/linux-64::geos-3.7.1-he6710b0_0
  giflib             pkgs/main/linux-64::giflib-5.1.4-h14c3975_1
  glib               pkgs/main/linux-64::glib-2.63.1-h5a9c865_0
  hdf4               pkgs/main/linux-64::hdf4-4.2.13-h3ca952b_2
  hdf5               pkgs/main/linux-64::hdf5-1.10.4-hb1b8bf9_0
  icu                pkgs/main/linux-64::icu-58.2-h9c2bf20_1
  intel-openmp       pkgs/main/linux-64::intel-openmp-2020.0-166
  jpeg               pkgs/main/linux-64::jpeg-9b-h024ee3a_2
  json-c             pkgs/main/linux-64::json-c-0.13.1-h1bed415_0
  kealib             pkgs/main/linux-64::kealib-1.4.12-hd0c454d_0
  krb5               pkgs/main/linux-64::krb5-1.16.4-h173b8e3_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.33.1-h53a641e_7
  libboost           pkgs/main/linux-64::libboost-1.67.0-h46d08c1_4
  libcurl            pkgs/main/linux-64::libcurl-7.67.0-h20c2e04_0
  libdap4            pkgs/main/linux-64::libdap4-3.19.1-h6ec2957_0
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             pkgs/main/linux-64::libffi-3.2.1-hd88cf55_4
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libgdal            pkgs/main/linux-64::libgdal-2.3.3-h2e7e64b_0
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-7.3.0-hdf63c60_0
  libkml             pkgs/main/linux-64::libkml-1.3.0-h590aaf7_4
  libnetcdf          pkgs/main/linux-64::libnetcdf-4.6.1-h11d0813_2
  libpng             pkgs/main/linux-64::libpng-1.6.37-hbc83047_0
  libpq              pkgs/main/linux-64::libpq-11.2-h20c2e04_0
  libspatialindex    pkgs/main/linux-64::libspatialindex-1.9.3-he6710b0_0
  libspatialite      pkgs/main/linux-64::libspatialite-4.3.0a-hb08deb6_19
  libssh2            pkgs/main/linux-64::libssh2-1.8.2-h1ba5d50_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  libtiff            pkgs/main/linux-64::libtiff-4.1.0-h2733197_0
  libuuid            pkgs/main/linux-64::libuuid-1.0.3-h1bed415_2
  libxcb             pkgs/main/linux-64::libxcb-1.13-h1bed415_1
  libxml2            pkgs/main/linux-64::libxml2-2.9.9-hea5a465_1
  mkl                pkgs/main/linux-64::mkl-2020.0-166
  mkl-service        pkgs/main/linux-64::mkl-service-2.3.0-py38he904b0f_0
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.0.15-py38ha843d7b_0
  mkl_random         pkgs/main/linux-64::mkl_random-1.1.0-py38h962f231_0
  munch              pkgs/main/noarch::munch-2.5.0-py_0
  ncurses            pkgs/main/linux-64::ncurses-6.1-he6710b0_1
  numpy              pkgs/main/linux-64::numpy-1.18.1-py38h4f9e942_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.18.1-py38hde5b4d6_1
  openjpeg           pkgs/main/linux-64::openjpeg-2.3.0-h05c96fa_1
  openssl            pkgs/main/linux-64::openssl-1.1.1d-h7b6447c_4
  pandas             pkgs/main/linux-64::pandas-1.0.1-py38h0573a6f_0
  pcre               pkgs/main/linux-64::pcre-8.43-he6710b0_0
  pip                pkgs/main/linux-64::pip-20.0.2-py38_1
  pixman             pkgs/main/linux-64::pixman-0.38.0-h7b6447c_0
  poppler            pkgs/main/linux-64::poppler-0.65.0-h581218d_1
  poppler-data       pkgs/main/linux-64::poppler-data-0.4.9-0
  proj4              pkgs/main/linux-64::proj4-5.2.0-he6710b0_1
  pyproj             pkgs/main/linux-64::pyproj-1.9.6-py38h14380d9_0
  python             pkgs/main/linux-64::python-3.8.1-h0371630_1
  python-dateutil    pkgs/main/noarch::python-dateutil-2.8.1-py_0
  pytz               pkgs/main/noarch::pytz-2019.3-py_0
  readline           pkgs/main/linux-64::readline-7.0-h7b6447c_5
  rtree              pkgs/main/linux-64::rtree-0.9.3-py38_0
  setuptools         pkgs/main/linux-64::setuptools-45.2.0-py38_0
  shapely            pkgs/main/linux-64::shapely-1.6.4-py38h86c5351_0
  six                pkgs/main/linux-64::six-1.14.0-py38_0
  sqlite             pkgs/main/linux-64::sqlite-3.31.1-h7b6447c_0
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.34.2-py38_0
  xerces-c           pkgs/main/linux-64::xerces-c-3.2.2-h780794e_0
  xz                 pkgs/main/linux-64::xz-5.2.4-h14c3975_4
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3
  zstd               pkgs/main/linux-64::zstd-1.3.7-h0b5b093_0


Proceed ([y]/n)? 


Downloading and Extracting Packages
...
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate geo_test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) $ conda activate geo_test
(geo_test) $ python
Python 3.8.1 (default, Jan  8 2020, 22:29:32) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joris/miniconda3/envs/geo_test/lib/python3.8/site-packages/fiona/__init__.py", line 83, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/home/joris/miniconda3/envs/geo_test/lib/python3.8/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libkea.so.1.4.7: cannot open shared object file: No such file or directory
>>> 
```

**Comment by ocefpaf** [comment]
@msarahan I recall there was a soname change from `1.4.7` to `1.4.8`. So a proper pin would be `kealib >=1.4.8,<1.5.0a0`.

**Comment by msarahan** [comment]
My last day at Anaconda was yesterday, but I'll ping @jjhelmus and @forrestwaters here. I had to impose a tighter upper bound on libnetcdf also. I think the bound here needs to be hotfixed to

`>=1.4.7,<1.4.8.0a0`

**Comment by ocefpaf** [comment]
> My last day at Anaconda was yesterday

Force of habit. sorry! Thanks for pinging the right people!

**Comment by jjhelmus** [comment]
I'll put together a hotfix for this issue this afternoon.

**Comment by jjhelmus** [comment]
The bounds on existing packages which depend on kealib have been hotfixed to express the correct bounds, `>=1.4.7,<1.4.8.0a0`.  Creating an environment with geopandas now works for me.  @jorisvandenbossche Can you confirm this fixes the issue?

**Comment by ocefpaf** [comment]
Thanks @jjhelmus for fixing this so quickly.

**Comment by jorisvandenbossche** [comment]
Yes, can confirm a fresh env is created correctly now. Thanks for the quick response!
